import type { RelicDefinition, Tactic } from './types';

export const EXTRA_TACTICS: Tactic[] = [
  {
    id: 'sun-flash',
    name: '해오름',
    description: '먹은 광 한 장마다 즉시 18점을 얻는다.',
    cost: 1,
    archetype: '광',
    rarity: '일반',
    tags: ['광', '득점'],
    effect: { type: 'score-kind', kind: '광', amount: 18 },
  },
  {
    id: 'star-map',
    name: '별자리 읽기',
    description: '이번 턴 모든 달을 맞는 것으로 취급한다.',
    cost: 2,
    archetype: '광',
    rarity: '희귀',
    tags: ['광', '탐색'],
    effect: { type: 'wild' },
  },
  {
    id: 'light-hook',
    name: '빛 낚시',
    description: '바닥에서 가장 값진 광을 가져온다.',
    cost: 2,
    archetype: '광',
    rarity: '희귀',
    tags: ['광', '포획'],
    effect: { type: 'snatch', kind: '광', highest: true },
  },
  {
    id: 'five-lights',
    name: '오광의 맹세',
    description: '현재 먹은 광 한 장마다 즉시 30점을 얻는다.',
    cost: 2,
    archetype: '광',
    rarity: '전설',
    tags: ['광', '완성'],
    effect: { type: 'score-kind', kind: '광', amount: 30 },
  },
  {
    id: 'red-thread',
    name: '홍실',
    description: '먹은 띠 한 장마다 즉시 12점을 얻는다.',
    cost: 1,
    archetype: '띠',
    rarity: '일반',
    tags: ['띠', '득점'],
    effect: { type: 'score-kind', kind: '띠', amount: 12 },
  },
  {
    id: 'blue-thread',
    name: '청실',
    description: '바닥에서 가장 값진 띠를 가져온다.',
    cost: 1,
    archetype: '띠',
    rarity: '일반',
    tags: ['띠', '포획'],
    effect: { type: 'snatch', kind: '띠', highest: true },
  },
  {
    id: 'ribbon-dance',
    name: '띠춤',
    description: '다음 포획에서 띠마다 28점을 추가한다.',
    cost: 1,
    archetype: '띠',
    rarity: '희귀',
    tags: ['띠', '포획'],
    effect: { type: 'capture-bonus', amount: 28, kind: '띠' },
  },
  {
    id: 'triple-knot',
    name: '삼색 매듭',
    description: '이번 판의 목표 점수를 18점 낮춘다.',
    cost: 2,
    archetype: '띠',
    rarity: '전설',
    tags: ['띠', '완성'],
    effect: { type: 'target-down', amount: 18 },
  },
  {
    id: 'bird-call',
    name: '새 부르기',
    description: '바닥의 열끗 한 장을 가져온다.',
    cost: 1,
    archetype: '열끗',
    rarity: '일반',
    tags: ['열끗', '포획'],
    effect: { type: 'snatch', kind: '열끗', highest: true },
  },
  {
    id: 'beast-trail',
    name: '짐승 발자국',
    description: '먹은 열끗 한 장마다 즉시 15점을 얻는다.',
    cost: 1,
    archetype: '열끗',
    rarity: '일반',
    tags: ['열끗', '득점'],
    effect: { type: 'score-kind', kind: '열끗', amount: 15 },
  },
  {
    id: 'crane-wing',
    name: '학의 날개',
    description: '다음 포획을 두 배로 계산한다.',
    cost: 2,
    archetype: '열끗',
    rarity: '희귀',
    tags: ['열끗', '포획'],
    effect: { type: 'double-capture' },
  },
  {
    id: 'wild-hunt',
    name: '고도리 사냥',
    description: '현재 먹은 열끗 한 장마다 즉시 25점을 얻는다.',
    cost: 2,
    archetype: '열끗',
    rarity: '전설',
    tags: ['열끗', '완성'],
    effect: { type: 'score-kind', kind: '열끗', amount: 25 },
  },
  {
    id: 'ash-sweep',
    name: '재 쓸기',
    description: '바닥의 피를 최대 두 장 쓸어온다.',
    cost: 1,
    archetype: '피',
    rarity: '일반',
    tags: ['피', '포획'],
    effect: { type: 'field-sweep', kind: '피', limit: 2 },
  },
  {
    id: 'seed-money',
    name: '밑천',
    description: '먹은 피 한 장마다 즉시 7점을 얻는다.',
    cost: 0,
    archetype: '피',
    rarity: '일반',
    tags: ['피', '득점'],
    effect: { type: 'score-kind', kind: '피', amount: 7 },
  },
  {
    id: 'rain-gutter',
    name: '빗물받이',
    description: '다음 포획에서 피마다 16점을 추가한다.',
    cost: 1,
    archetype: '피',
    rarity: '희귀',
    tags: ['피', '포획'],
    effect: { type: 'capture-bonus', amount: 16, kind: '피' },
  },
  {
    id: 'ten-junk',
    name: '피박의 예고',
    description: '목표 점수를 24점 낮춘다.',
    cost: 2,
    archetype: '피',
    rarity: '전설',
    tags: ['피', '완성'],
    effect: { type: 'target-down', amount: 24 },
  },
  {
    id: 'echo-hit',
    name: '메아리치기',
    description: '다음 포획에 24점을 더한다.',
    cost: 1,
    archetype: '포획',
    rarity: '일반',
    tags: ['포획', '연쇄'],
    effect: { type: 'capture-bonus', amount: 24 },
  },
  {
    id: 'moon-net',
    name: '달그물',
    description: '이번 턴 모든 달을 맞는 것으로 취급한다.',
    cost: 2,
    archetype: '포획',
    rarity: '희귀',
    tags: ['포획', '월'],
    effect: { type: 'wild' },
  },
  {
    id: 'golden-hook',
    name: '금갈고리',
    description: '바닥에서 가장 값진 패를 가져온다.',
    cost: 2,
    archetype: '포획',
    rarity: '희귀',
    tags: ['포획'],
    effect: { type: 'snatch', highest: true },
  },
  {
    id: 'grand-sweep',
    name: '판쓸이',
    description: '다음 포획에 60점을 더한다.',
    cost: 3,
    archetype: '포획',
    rarity: '전설',
    tags: ['포획', '연쇄'],
    effect: { type: 'capture-bonus', amount: 60 },
  },
  {
    id: 'ink-wash',
    name: '먹물 씻기',
    description: '사용한 전술 한 장을 다시 사용할 수 있게 한다.',
    cost: 2,
    archetype: '판술',
    rarity: '희귀',
    tags: ['판술', '순환'],
    effect: { type: 'reset-tactics', amount: 1 },
  },
  {
    id: 'deep-breath',
    name: '깊은 숨',
    description: '기력 2를 회복한다.',
    cost: 0,
    archetype: '판술',
    rarity: '일반',
    tags: ['판술', '기력'],
    effect: { type: 'energy', amount: 2 },
  },
  {
    id: 'stacked-deck',
    name: '패산 고르기',
    description: '덱 위에서 가장 유리한 패를 올린다.',
    cost: 1,
    archetype: '판술',
    rarity: '일반',
    tags: ['판술', '탐색'],
    effect: { type: 'peek', amount: 5 },
  },
  {
    id: 'all-night',
    name: '밤샘 판술',
    description: '모든 전술을 다시 사용할 수 있게 한다.',
    cost: 3,
    archetype: '판술',
    rarity: '전설',
    tags: ['판술', '순환'],
    effect: { type: 'reset-tactics', amount: 99 },
  },
  {
    id: 'cold-gaze',
    name: '찬 눈초리',
    description: '다음 상대 한 명의 차례를 막는다.',
    cost: 1,
    archetype: '견제',
    rarity: '일반',
    tags: ['견제', '봉쇄'],
    effect: { type: 'skip', amount: 1 },
  },
  {
    id: 'sealed-room',
    name: '문 걸어 잠그기',
    description: '다음 상대 두 명의 차례를 막는다.',
    cost: 3,
    archetype: '견제',
    rarity: '희귀',
    tags: ['견제', '봉쇄'],
    effect: { type: 'skip', amount: 2 },
  },
  {
    id: 'false-deal',
    name: '헛패 돌리기',
    description: '죽은 손패를 최대 두 장 교환한다.',
    cost: 2,
    archetype: '견제',
    rarity: '희귀',
    tags: ['견제', '교환'],
    effect: { type: 'swap', amount: 2 },
  },
  {
    id: 'red-seal',
    name: '붉은 봉인',
    description: '상대를 묶고 즉시 20점을 얻는다.',
    cost: 2,
    archetype: '견제',
    rarity: '전설',
    tags: ['견제', '봉쇄'],
    effect: { type: 'skip', amount: 1 },
  },
  {
    id: 'raise-stakes',
    name: '판돈 올리기',
    description: '이번 판의 고 보너스를 20% 올린다.',
    cost: 1,
    archetype: '고',
    rarity: '일반',
    tags: ['고', '위험'],
    effect: { type: 'go-bonus', amount: 0.2 },
  },
  {
    id: 'last-gamble',
    name: '마지막 승부',
    description: '즉시 35점을 얻지만 목표도 10점 오른다.',
    cost: 1,
    archetype: '고',
    rarity: '희귀',
    tags: ['고', '위험'],
    effect: { type: 'score-flat', amount: 35 },
  },
  {
    id: 'double-or-nothing',
    name: '모 아니면 도',
    description: '다음 포획에 80점을 더한다.',
    cost: 3,
    archetype: '고',
    rarity: '전설',
    tags: ['고', '위험', '포획'],
    effect: { type: 'capture-bonus', amount: 80 },
  },
  {
    id: 'victory-toast',
    name: '승전주',
    description: '고 횟수마다 즉시 30점을 얻는다.',
    cost: 2,
    archetype: '고',
    rarity: '희귀',
    tags: ['고', '득점'],
    effect: { type: 'score-flat', amount: 0 },
  },
];

export const EXTRA_RELICS: RelicDefinition[] = [
  {
    id: 'sun-stamp',
    name: '해 도장',
    description: '먹은 광 한 장마다 12점.',
    build: '광',
    rarity: '일반',
    effects: [{ type: 'score-per-kind', kind: '광', amount: 12 }],
  },
  {
    id: 'dawn-lantern',
    name: '새벽 등롱',
    description: '광을 먹는 포획마다 18점.',
    build: '광',
    rarity: '희귀',
    effects: [{ type: 'capture-kind-bonus', kind: '광', amount: 18 }],
  },
  {
    id: 'red-inkstone',
    name: '붉은 벼루',
    description: '먹은 띠 한 장마다 7점.',
    build: '띠',
    rarity: '일반',
    effects: [{ type: 'score-per-kind', kind: '띠', amount: 7 }],
  },
  {
    id: 'ribbon-needle',
    name: '띠바늘',
    description: '띠를 먹는 포획마다 14점.',
    build: '띠',
    rarity: '희귀',
    effects: [{ type: 'capture-kind-bonus', kind: '띠', amount: 14 }],
  },
  {
    id: 'boar-tusk',
    name: '멧돼지 엄니',
    description: '먹은 열끗 한 장마다 9점.',
    build: '열끗',
    rarity: '일반',
    effects: [{ type: 'score-per-kind', kind: '열끗', amount: 9 }],
  },
  {
    id: 'sparrow-nest',
    name: '참새 둥지',
    description: '열끗을 먹으면 기력 1 회복.',
    build: '열끗',
    rarity: '희귀',
    effects: [{ type: 'energy-on-kind', kind: '열끗', amount: 1 }],
  },
  {
    id: 'ash-purse',
    name: '재주머니',
    description: '먹은 피 한 장마다 4점.',
    build: '피',
    rarity: '일반',
    effects: [{ type: 'score-per-kind', kind: '피', amount: 4 }],
  },
  {
    id: 'rain-bowl',
    name: '빗물 사발',
    description: '피를 먹는 포획마다 10점.',
    build: '피',
    rarity: '희귀',
    effects: [{ type: 'capture-kind-bonus', kind: '피', amount: 10 }],
  },
  {
    id: 'echo-drum',
    name: '메아리 북',
    description: '사용한 전술 한 장마다 14점.',
    build: '판술',
    rarity: '희귀',
    effects: [{ type: 'score-per-tactic', amount: 14 }],
  },
  {
    id: 'jade-battery',
    name: '옥 기력패',
    description: '기력 상한이 1 증가한다.',
    build: '판술',
    rarity: '전설',
    effects: [{ type: 'max-energy', amount: 1 }],
  },
  {
    id: 'ink-brush',
    name: '먹붓',
    description: '판술 태그 전술의 비용이 1 감소한다.',
    build: '판술',
    rarity: '희귀',
    effects: [{ type: 'tag-cost-down', tag: '판술', amount: 1 }],
  },
  {
    id: 'first-snow',
    name: '첫눈 병',
    description: '매 대국 시작 기력 +1.',
    build: '판술',
    rarity: '일반',
    effects: [{ type: 'start-energy', amount: 1 }],
  },
  {
    id: 'pressed-flower',
    name: '압화첩',
    description: '한 번에 4장 이상 먹으면 30점.',
    build: '포획',
    rarity: '희귀',
    effects: [{ type: 'capture-chain-bonus', threshold: 4, amount: 30 }],
  },
  {
    id: 'chain-bell',
    name: '연쇄 방울',
    description: '한 번에 4장 이상 먹으면 기력 1 회복.',
    build: '포획',
    rarity: '희귀',
    effects: [{ type: 'energy-on-chain', threshold: 4, amount: 1 }],
  },
  {
    id: 'gambler-mask',
    name: '노름꾼 탈',
    description: '고마다 최종 점수 배율 +15%.',
    build: '고',
    rarity: '전설',
    effects: [{ type: 'go-multiplier', amount: 0.15 }],
  },
  {
    id: 'four-season-screen',
    name: '사계 병풍',
    description: '네 종류 패를 모두 먹으면 80점.',
    build: '포획',
    rarity: '전설',
    effects: [{ type: 'score-four-kinds', amount: 80 }],
  },
  {
    id: 'sealed-ink',
    name: '봉인 먹',
    description: '견제 태그 전술의 비용이 1 감소한다.',
    build: '견제',
    rarity: '희귀',
    effects: [{ type: 'tag-cost-down', tag: '견제', amount: 1 }],
  },
  {
    id: 'watchman-knot',
    name: '문지기 매듭',
    description: '막아낸 상대 차례마다 24점.',
    build: '견제',
    rarity: '전설',
    effects: [{ type: 'score-per-skip', amount: 24 }],
  },
  {
    id: 'pi-string',
    name: '피 엮은 노끈',
    description: '피를 먹으면 기력 1 회복.',
    build: '피',
    rarity: '희귀',
    effects: [{ type: 'energy-on-kind', kind: '피', amount: 1 }],
  },
];
