import type { BossDefinition } from "../types";

export const BOSSES = [
  {
    id: "boss_falling_first",
    name: "낙화",
    description: "매 제출에서 맨 왼쪽 첫 득점 카드의 월값이 0이 됨.",
    ruleKey: "first_card_zero",
    counterplay: "카드 순서를 바꾸고 월값이 낮은 카드를 첫 칸에 배치.",
    assetTag: "boss:falling-first",
  },
  {
    id: "boss_drought",
    name: "가뭄",
    description: "비 그림이 있는 패와 12월 패는 이번 판에 득점하지 않음.",
    ruleKey: "no_rain",
    counterplay: "다른 월을 중심으로 득점하거나 두목 교체를 사용.",
    assetTag: "boss:drought",
  },
  {
    id: "boss_monsoon",
    name: "장마",
    description: "비 그림이 없는 광 카드의 월값이 0이 됨.",
    ruleKey: "dry_bright",
    counterplay: "월 족보와 비 그림이 있는 패로 우회.",
    assetTag: "boss:monsoon",
  },
  {
    id: "boss_dark_cloud",
    name: "먹구름",
    description: "광은 족보 판정에 참여하지만 월값이 0이 됨.",
    ruleKey: "bright_zero",
    counterplay: "광을 짓패보다 끗패로 먼저 고르거나 월 합을 더하는 부적으로 보완.",
    assetTag: "boss:dark-cloud",
  },
  {
    id: "boss_ribbon_scissors",
    name: "띠 끊는 가위",
    description: "첫 제출의 띠 카드는 즉시 족보와 수집 족보 판정에 참여하지 않음.",
    ruleKey: "first_ribbon_disabled",
    counterplay: "첫 제출을 다른 족보에 사용하고 이후 띠를 모음.",
    assetTag: "boss:ribbon-scissors",
  },
  {
    id: "boss_lost_moon",
    name: "짝 잃은 달",
    description: "직전 판에서 가장 많이 득점한 월 카드의 월값이 절반으로 감소.",
    ruleKey: "popular_month_weak",
    counterplay: "자주 쓰던 월에만 기대지 말고 다른 월과 종류 조합도 준비.",
    assetTag: "boss:lost-pair-moon",
  },
  {
    id: "boss_tax_collector",
    name: "세금쟁이",
    description: "버리기를 사용할 때마다 1냥을 지불. 돈이 없으면 버릴 수 없음.",
    ruleKey: "discard_tax",
    counterplay: "버리기를 아끼거나 경제 부적과 계약을 준비.",
    assetTag: "boss:tax-collector",
  },
  {
    id: "boss_reversed_screen",
    name: "뒤집힌 병풍",
    description: "매 보충 때 무작위 카드 2장이 뒷면으로 들어옴.",
    ruleKey: "two_face_down",
    counterplay: "뒷면 카드를 선택해 정보를 공개하고 이미 본 카드를 기억.",
    assetTag: "boss:reversed-screen",
  },
  {
    id: "boss_stubborn",
    name: "고집쟁이",
    description: "고를 한 번 성공시킨 뒤 스톱해야 이 판을 통과할 수 있음.",
    ruleKey: "requires_go",
    counterplay: "이번 승부 점수가 작을 때 먼저 1고를 시도해 조건을 확보.",
    assetTag: "boss:stubborn",
  },
  {
    id: "boss_go_bak",
    name: "고박",
    description: "고 실패 시 이미 확정한 점수도 10% 감소.",
    ruleKey: "go_fail_tax",
    counterplay: "확실한 손에서만 고하거나 실패 구제 효과를 준비.",
    assetTag: "boss:go-bond",
  },
  {
    id: "boss_reverse_calendar",
    name: "안개 병풍",
    description: "패를 보충할 때마다 새로 들어온 카드 두 장이 뒷면으로 놓임.",
    ruleKey: "two_face_down",
    counterplay: "뒷면 패를 먼저 눌러 확인한 뒤 끗패 두 장의 선택 순서를 정함.",
    assetTag: "boss:fog-screen",
  },
  {
    id: "boss_nagari_king",
    name: "나가리 왕",
    description: "고 성공이 없는 0고 정산은 이번 승부 점수의 80%만 확정.",
    ruleKey: "zero_go_reduced",
    counterplay: "고를 한 번 성공시키거나 한 번의 제출 점수를 크게 키움.",
    assetTag: "boss:nagari-king",
  },
] as const satisfies readonly BossDefinition[];

export const BOSS_BY_ID = Object.fromEntries(
  BOSSES.map((definition) => [definition.id, definition]),
) as Record<string, (typeof BOSSES)[number]>;
