import type { BossDefinition } from "../types";

export const BOSSES = [
  {
    id: "boss_falling_first",
    name: "낙화",
    description: "매 제출에서 맨 왼쪽 첫 득점 카드의 월값이 0이 됨.",
    ruleKey: "first_card_zero",
    counterplay: "카드 순서를 바꾸고 월값이 낮은 카드를 첫 칸에 배치.",
    assetTag: "boss:falling-first",
  },
  {
    id: "boss_drought",
    name: "가뭄",
    description: "비 태그 카드와 12월 카드는 이번 판에 득점하지 않음.",
    ruleKey: "no_rain",
    counterplay: "다른 월을 중심으로 득점하거나 두목 교체를 사용.",
    assetTag: "boss:drought",
  },
  {
    id: "boss_monsoon",
    name: "장마",
    description: "비 태그가 아닌 광 카드의 월값이 0이 됨.",
    ruleKey: "dry_bright",
    counterplay: "월 족보와 비 태그 카드로 우회.",
    assetTag: "boss:monsoon",
  },
  {
    id: "boss_dark_cloud",
    name: "먹구름",
    description: "광은 족보 판정에 참여하지만 월값이 0이 됨.",
    ruleKey: "bright_zero",
    counterplay: "월 합 추가 효과나 월쌍·연월 족보로 잃은 월값을 보완.",
    assetTag: "boss:dark-cloud",
  },
  {
    id: "boss_ribbon_scissors",
    name: "띠 끊는 가위",
    description: "첫 제출의 띠 카드는 즉시 족보와 수집 족보 판정에 참여하지 않음.",
    ruleKey: "first_ribbon_disabled",
    counterplay: "첫 제출을 다른 족보에 사용하고 이후 띠를 모음.",
    assetTag: "boss:ribbon-scissors",
  },
  {
    id: "boss_lost_moon",
    name: "짝 잃은 달",
    description: "직전 판에서 가장 많이 득점한 월 카드의 월값이 절반으로 감소.",
    ruleKey: "popular_month_weak",
    counterplay: "두 번째로 강한 월·종류 엔진을 준비.",
    assetTag: "boss:lost-pair-moon",
  },
  {
    id: "boss_tax_collector",
    name: "세금쟁이",
    description: "버리기를 사용할 때마다 1냥을 지불. 돈이 없으면 버릴 수 없음.",
    ruleKey: "discard_tax",
    counterplay: "버리기를 아끼거나 경제 부적과 계약을 준비.",
    assetTag: "boss:tax-collector",
  },
  {
    id: "boss_reversed_screen",
    name: "뒤집힌 병풍",
    description: "매 보충 때 무작위 카드 2장이 뒷면으로 들어옴.",
    ruleKey: "two_face_down",
    counterplay: "뒷면 카드를 선택해 정보를 공개하고 이미 본 카드를 기억.",
    assetTag: "boss:reversed-screen",
  },
  {
    id: "boss_stubborn",
    name: "고집쟁이",
    description: "성공한 고가 포함된 안전 정산을 최소 1회 해야 클리어 가능.",
    ruleKey: "requires_go",
    counterplay: "이번 승부 점수가 작을 때 먼저 1고를 시도해 조건을 확보.",
    assetTag: "boss:stubborn",
  },
  {
    id: "boss_go_bak",
    name: "고박",
    description: "고 실패 시 이미 확정한 점수도 10% 감소.",
    ruleKey: "go_fail_tax",
    counterplay: "확실한 손에서만 고하거나 실패 구제 효과를 준비.",
    assetTag: "boss:go-bond",
  },
  {
    id: "boss_reverse_calendar",
    name: "역달력",
    description: "연월 족보는 월을 내림차순으로 배치했을 때만 성립.",
    ruleKey: "reverse_runs",
    counterplay: "미리보기 안내에 맞춰 카드 순서를 역순으로 정렬.",
    assetTag: "boss:reverse-calendar",
  },
  {
    id: "boss_nagari_king",
    name: "나가리 왕",
    description: "고 성공이 없는 0고 정산은 이번 승부 점수의 80%만 확정.",
    ruleKey: "zero_go_reduced",
    counterplay: "고 엔진을 사용하거나 손 하나의 점수를 크게 키움.",
    assetTag: "boss:nagari-king",
  },
] as const satisfies readonly BossDefinition[];

export const BOSS_BY_ID = Object.fromEntries(
  BOSSES.map((definition) => [definition.id, definition]),
) as Record<string, (typeof BOSSES)[number]>;
