import type { TalismanDefinition } from "../types";

/**
 * 전체 부적 카탈로그. effectKey는 엔진의 큰 처리 축을, params는 개별
 * 부적의 조건과 한도를 설명한다. assetTag는 추후 원본 에셋을 연결할
 * 때 사용하는 안정적인 논리 키다.
 */
export const TALISMANS = [
  {
    id: "t_first_charm",
    name: "첫 부적",
    description: "어떤 족보로 내든 배수 +4.",
    rarity: "common",
    price: 5,
    weight: 18,
    effectKey: "yaku_add_heung",
    amount: 4,
    assetTag: "talisman:first-charm",
  },
  {
    id: "t_pine_needles",
    name: "솔잎 부적",
    description: "득점하는 1~3월 카드마다 월 합 +4.",
    rarity: "common",
    price: 5,
    weight: 25,
    effectKey: "season_cards_add_kkeut",
    amount: 4,
    params: { monthFrom: 1, monthTo: 3 },
    assetTag: "talisman:pine-needles",
  },
  {
    id: "t_peony_bloom",
    name: "모란 부적",
    description: "득점하는 4~6월 카드마다 월 합 +4.",
    rarity: "common",
    price: 5,
    weight: 25,
    effectKey: "season_cards_add_kkeut",
    amount: 4,
    params: { monthFrom: 4, monthTo: 6 },
    assetTag: "talisman:peony-bloom",
  },
  {
    id: "t_maple_leaf",
    name: "단풍 부적",
    description: "득점하는 7~9월 카드마다 월 합 +4.",
    rarity: "common",
    price: 5,
    weight: 25,
    effectKey: "season_cards_add_kkeut",
    amount: 4,
    params: { monthFrom: 7, monthTo: 9 },
    assetTag: "talisman:maple-leaf",
  },
  {
    id: "t_snow_rain",
    name: "눈비 부적",
    description: "득점하는 10~12월 카드마다 월 합 +4.",
    rarity: "common",
    price: 5,
    weight: 25,
    effectKey: "season_cards_add_kkeut",
    amount: 4,
    params: { monthFrom: 10, monthTo: 12 },
    assetTag: "talisman:snow-rain",
  },
  {
    id: "t_chaff_bind",
    name: "피붙이",
    description: "득점한 피값 1마다 월 합 +3.",
    rarity: "common",
    price: 5,
    weight: 25,
    effectKey: "chaff_value_add_kkeut",
    amount: 3,
    assetTag: "talisman:chaff-bind",
  },
  {
    id: "t_ribbon_maker",
    name: "띠장이",
    description: "득점하는 띠 카드마다 월 합 +5.",
    rarity: "common",
    price: 5,
    weight: 25,
    effectKey: "kind_cards_add_kkeut",
    amount: 5,
    params: { kind: "ribbon" },
    assetTag: "talisman:ribbon-maker",
  },
  {
    id: "t_animal_tracks",
    name: "산짐승 발자국",
    description: "득점하는 동물패마다 월 합 +6.",
    rarity: "common",
    price: 5,
    weight: 25,
    effectKey: "kind_cards_add_kkeut",
    amount: 6,
    params: { kind: "animal" },
    assetTag: "talisman:animal-tracks",
  },
  {
    id: "t_bright_polish",
    name: "광약",
    description: "득점하는 광 카드마다 월 합 +10.",
    rarity: "common",
    price: 6,
    weight: 20,
    effectKey: "kind_cards_add_kkeut",
    amount: 10,
    params: { kind: "bright" },
    assetTag: "talisman:bright-polish",
  },
  {
    id: "t_five_fingers",
    name: "다섯 손가락",
    description: "정확히 5장을 제출하면 월 합 +12와 배수 +1.",
    rarity: "common",
    price: 6,
    weight: 20,
    effectKey: "exact_submit_add",
    amount: 12,
    params: { cardCount: 5, addHeung: 1 },
    assetTag: "talisman:five-fingers",
  },
  {
    id: "t_lone_merchant",
    name: "독장수",
    description: "정확히 1장만 득점하면 월 합 +18과 배수 +2.",
    rarity: "common",
    price: 6,
    weight: 20,
    effectKey: "exact_scoring_add",
    amount: 18,
    params: { scoringCardCount: 1, addHeung: 2 },
    assetTag: "talisman:lone-merchant",
  },
  {
    id: "t_pair_knot",
    name: "짝패 매듭",
    description: "월쌍 또는 두쌍이면 배수 +2.",
    rarity: "common",
    price: 6,
    weight: 20,
    effectKey: "yaku_add_heung",
    amount: 2,
    params: { yakuIds: "month_pair,two_pairs" },
    assetTag: "talisman:pair-knot",
  },
  {
    id: "t_early_home",
    name: "조기 귀가",
    description: "판을 이길 때 남은 제출 1회마다 추가로 1냥을 얻음.",
    rarity: "common",
    price: 5,
    weight: 20,
    effectKey: "economy",
    amount: 1,
    params: { trigger: "round_win", perRemainingHand: true },
    assetTag: "talisman:early-home",
  },

  {
    id: "t_hong_thread",
    name: "홍실 매듭",
    description: "홍단을 새로 완성하면 배수 +4.",
    rarity: "uncommon",
    price: 7,
    weight: 14,
    effectKey: "collection_add_heung",
    amount: 4,
    params: { yakuId: "hongdan" },
    assetTag: "talisman:hong-thread",
  },
  {
    id: "t_cho_thread",
    name: "풀실 매듭",
    description: "초단을 새로 완성하면 배수 +4.",
    rarity: "uncommon",
    price: 7,
    weight: 14,
    effectKey: "collection_add_heung",
    amount: 4,
    params: { yakuId: "chodan" },
    assetTag: "talisman:cho-thread",
  },
  {
    id: "t_cheong_thread",
    name: "청실 매듭",
    description: "청단을 새로 완성하면 배수 +4.",
    rarity: "uncommon",
    price: 7,
    weight: 14,
    effectKey: "collection_add_heung",
    amount: 4,
    params: { yakuId: "cheongdan" },
    assetTag: "talisman:cheong-thread",
  },
  {
    id: "t_migratory_map",
    name: "철새 지도",
    description: "득점하는 새 태그 카드의 득점 효과를 1회 재발동.",
    rarity: "uncommon",
    price: 8,
    weight: 12,
    effectKey: "bird_retrigger",
    amount: 1,
    params: { tag: "bird" },
    assetTag: "talisman:migratory-map",
  },
  {
    id: "t_double_chaff_belt",
    name: "쌍피 전대",
    description: "피 카드의 피값이 1 늘고, 쌍피가 득점하면 월 합 +10.",
    rarity: "uncommon",
    price: 8,
    weight: 12,
    effectKey: "double_chaff_boost",
    amount: 10,
    params: { chaffValueBonus: 1 },
    assetTag: "talisman:double-chaff-belt",
  },
  {
    id: "t_leap_calendar",
    name: "윤달 달력",
    description: "연월 족보에서 12월과 1월이 서로 이어짐.",
    rarity: "uncommon",
    price: 7,
    weight: 10,
    effectKey: "connect_year",
    params: { appliesTo: "run_yakus" },
    assetTag: "talisman:leap-calendar",
  },
  {
    id: "t_empty_pouch",
    name: "빈 부적집",
    description: "비어 있는 부적 슬롯마다 배수 +1.",
    rarity: "uncommon",
    price: 7,
    weight: 12,
    effectKey: "empty_slots_add_heung",
    amount: 1,
    assetTag: "talisman:empty-pouch",
  },
  {
    id: "t_ring_ledger",
    name: "고리 장부",
    description: "보유 5냥마다 배수 +1, 최대 배수 +6.",
    rarity: "uncommon",
    price: 8,
    weight: 12,
    effectKey: "money_add_heung",
    amount: 1,
    params: { moneyStep: 5, maxHeung: 6 },
    assetTag: "talisman:ring-ledger",
  },
  {
    id: "t_shake_iron",
    name: "흔들쇠",
    description: "흔들기를 선언할 때 이 부적이 주는 배수가 영구적으로 +1 성장.",
    rarity: "uncommon",
    price: 8,
    weight: 10,
    effectKey: "yaku_add_heung",
    amount: 1,
    params: { trigger: "shake_declared", permanentGrowth: true },
    assetTag: "talisman:shake-iron",
  },
  {
    id: "t_sweep_broom",
    name: "싹쓸이 빗자루",
    description: "제출한 카드가 모두 득점하면 월 합 +20과 배수 +2.",
    rarity: "uncommon",
    price: 8,
    weight: 12,
    effectKey: "all_cards_score_bonus",
    amount: 20,
    params: { addHeung: 2 },
    assetTag: "talisman:sweep-broom",
  },
  {
    id: "t_mutual_aid",
    name: "품앗이",
    description: "첫 득점 카드에 손질이 있으면 그 카드의 득점 효과를 1회 재발동.",
    rarity: "uncommon",
    price: 8,
    weight: 10,
    effectKey: "first_card_retrigger",
    amount: 1,
    params: { requiresEnhancement: true },
    assetTag: "talisman:mutual-aid",
  },
  {
    id: "t_market_rumor",
    name: "장터 소문",
    description: "상점 첫 리롤은 무료지만 이후 리롤 비용 증가량이 +1 커짐.",
    rarity: "uncommon",
    price: 7,
    weight: 10,
    effectKey: "economy",
    params: { firstRerollFree: true, extraRerollIncrement: 1 },
    assetTag: "talisman:market-rumor",
  },

  {
    id: "t_goblin_mirror",
    name: "도깨비 거울",
    description: "바로 왼쪽 부적의 점수 효과를 복사. 거울과 경제 효과는 복사하지 않음.",
    rarity: "rare",
    price: 11,
    weight: 6,
    effectKey: "copy_left_score",
    params: { excludesCopy: true, excludesEconomy: true },
    assetTag: "talisman:goblin-mirror",
  },
  {
    id: "t_chrysanthemum_cup",
    name: "국진 술잔",
    description: "9월 술잔이 동물패와 쌍피를 동시에 만족하고 득점 효과를 1회 재발동.",
    rarity: "rare",
    price: 11,
    weight: 6,
    effectKey: "cup_dual_role",
    amount: 1,
    params: { simultaneousRoles: true },
    assetTag: "talisman:chrysanthemum-cup",
  },
  {
    id: "t_full_moon_screen",
    name: "만월 병풍",
    description: "8월 카드는 족보 판정에서 광으로도 취급.",
    rarity: "rare",
    price: 10,
    weight: 6,
    effectKey: "month_counts_as_bright",
    params: { month: 8 },
    assetTag: "talisman:full-moon-screen",
  },
  {
    id: "t_cardsharp_touch",
    name: "타짜의 손끝",
    description: "각 손의 첫 득점 카드를 2회 추가 발동.",
    rarity: "rare",
    price: 12,
    weight: 5,
    effectKey: "first_card_retrigger",
    amount: 2,
    assetTag: "talisman:cardsharp-touch",
  },
  {
    id: "t_cremation_deed",
    name: "화형 문서",
    description: "손마다 첫 득점 피 1장을 종료 후 소각하고, 라운드당 한 번 배수가 영구적으로 +0.08 성장.",
    rarity: "rare",
    price: 11,
    weight: 5,
    effectKey: "burn_chaff_growth",
    factor: 1.08,
    params: { growthPerBurn: 0.08, maxGrowthsPerRound: 1 },
    assetTag: "talisman:cremation-deed",
  },
  {
    id: "t_twelve_panel_calendar",
    name: "열두 폭 달력",
    description: "이번 라운드에 처음 득점한 서로 다른 월마다 배수가 +0.15 성장하고 라운드마다 초기화.",
    rarity: "rare",
    price: 11,
    weight: 5,
    effectKey: "month_diversity_multiplier",
    factor: 0.15,
    params: { resetEachRound: true },
    assetTag: "talisman:twelve-panel-calendar",
  },
  {
    id: "t_go_bond_deed",
    name: "고박 문서",
    description: "고에 성공한 이번 승부의 배수를 ×1.5. 고 실패 시 2냥을 잃음.",
    rarity: "rare",
    price: 11,
    weight: 5,
    effectKey: "go_chain_multiplier",
    factor: 1.5,
    params: { failMoneyLoss: 2 },
    assetTag: "talisman:go-bond-deed",
  },
  {
    id: "t_over_shoulder_secret",
    name: "어깨너머 비법",
    description: "각 족보는 자기 레벨과 가장 높은 족보 레벨-2 중 큰 값을 사용.",
    rarity: "rare",
    price: 12,
    weight: 4,
    effectKey: "borrow_yaku_level",
    params: { highestLevelOffset: 2 },
    assetTag: "talisman:over-shoulder-secret",
  },

  {
    id: "t_twelve_month_painter",
    name: "열두 달의 화공",
    description: "라운드당 1회, 제출 카드의 월을 이번 판정에서 하나의 선택 월로 통일.",
    rarity: "legendary",
    price: 15,
    weight: 1,
    effectKey: "unify_month_once",
    params: { usesPerRound: 1 },
    assetTag: "talisman:twelve-month-painter",
  },
  {
    id: "t_five_direction_goblin",
    name: "오방 도깨비",
    description: "제출 카드는 족보 판정에서 모든 종류로 취급하지만 점수는 각 카드의 원래 월값으로 계산.",
    rarity: "legendary",
    price: 16,
    weight: 1,
    effectKey: "all_kind_wild",
    params: { naturalKkeutOnly: true },
    assetTag: "talisman:five-direction-goblin",
  },
  {
    id: "t_phoenix_seal",
    name: "불사조의 인장",
    description: "라운드에서 처음 소각된 일반 카드가 무작위 판본을 얻은 복사본 2장으로 돌아옴.",
    rarity: "legendary",
    price: 16,
    weight: 1,
    effectKey: "score_then_burn",
    params: { trigger: "first_burn_each_round", copies: 2, randomEdition: true },
    assetTag: "talisman:phoenix-seal",
  },
  {
    id: "t_table_reader",
    name: "판을 읽는 자",
    description: "가장 오른쪽의 복사 불가 부적 점수 효과를 1회 더 발동.",
    rarity: "legendary",
    price: 16,
    weight: 1,
    effectKey: "copy_neighbors",
    amount: 1,
    params: { target: "rightmost_noncopyable" },
    assetTag: "talisman:table-reader",
  },
] as const satisfies readonly TalismanDefinition[];

export const TALISMAN_BY_ID = Object.fromEntries(
  TALISMANS.map((definition) => [definition.id, definition]),
) as Record<string, (typeof TALISMANS)[number]>;
