import type { TalismanDefinition } from "../types";

/**
 * 전체 부적 카탈로그. effectKey는 엔진의 큰 처리 축을, params는 개별
 * 부적의 조건과 한도를 설명한다. assetTag는 추후 원본 에셋을 연결할
 * 때 사용하는 안정적인 논리 키다.
 */
export const TALISMANS = [
  {
    id: "t_first_charm",
    name: "첫 부적",
    description: "어떤 족보로 내든 배수 +4.",
    rarity: "common",
    price: 5,
    weight: 18,
    effectKey: "yaku_add_heung",
    amount: 4,
    assetTag: "talisman:first-charm",
  },
  {
    id: "t_gambler_gut",
    name: "노름꾼의 배짱",
    description: "가진 냥 3냥마다 배수 +1. 최대 +10.",
    rarity: "uncommon",
    price: 7,
    weight: 12,
    effectKey: "money_add_heung",
    amount: 1,
    params: { moneyStep: 3, maxHeung: 10 },
    assetTag: "talisman:gambler-gut",
  },
  {
    id: "t_empty_shrine",
    name: "빈 사당",
    description: "비어 있는 부적 칸마다 배수 +3.",
    rarity: "uncommon",
    price: 7,
    weight: 12,
    effectKey: "empty_slots_add_heung",
    amount: 3,
    assetTag: "talisman:empty-shrine",
  },
  {
    id: "t_twelve_moons",
    name: "열두 달의 눈",
    description: "이번 판에 득점한 서로 다른 월 하나마다 배수 ×1.15.",
    rarity: "rare",
    price: 9,
    weight: 7,
    effectKey: "month_diversity_multiplier",
    factor: 0.15,
    assetTag: "talisman:twelve-moons",
  },
  {
    id: "t_lone_blade",
    name: "외날",
    description: "정확히 두 장만 내면 월 합 +60, 배수 +6. 짓 없이도 셉니다.",
    rarity: "uncommon",
    price: 6,
    weight: 11,
    effectKey: "exact_submit_add",
    amount: 60,
    params: { cardCount: 2, addHeung: 6 },
    assetTag: "talisman:lone-blade",
  },
  {
    id: "t_magpie_echo",
    name: "까치 메아리",
    description: "득점하는 새 그림패가 한 번씩 더 발동.",
    rarity: "rare",
    price: 9,
    weight: 8,
    effectKey: "bird_retrigger",
    amount: 1,
    params: { tag: "bird" },
    assetTag: "talisman:magpie-echo",
  },
  {
    id: "t_bright_hoard",
    name: "광 곳간",
    description: "득점하는 광 카드마다 월 합 +36.",
    rarity: "rare",
    price: 9,
    weight: 8,
    effectKey: "kind_cards_add_kkeut",
    amount: 36,
    params: { kind: "bright" },
    assetTag: "talisman:bright-hoard",
  },
  {
    id: "t_pine_needles",
    name: "솔잎 부적",
    description: "득점하는 1~3월 카드마다 월 합 +12.",
    rarity: "common",
    price: 5,
    weight: 25,
    effectKey: "season_cards_add_kkeut",
    amount: 12,
    params: { monthFrom: 1, monthTo: 3 },
    assetTag: "talisman:pine-needles",
  },
  {
    id: "t_peony_bloom",
    name: "모란 부적",
    description: "득점하는 4~6월 카드마다 월 합 +12.",
    rarity: "common",
    price: 5,
    weight: 25,
    effectKey: "season_cards_add_kkeut",
    amount: 12,
    params: { monthFrom: 4, monthTo: 6 },
    assetTag: "talisman:peony-bloom",
  },
  {
    id: "t_maple_leaf",
    name: "단풍 부적",
    description: "득점하는 7~9월 카드마다 월 합 +12.",
    rarity: "common",
    price: 5,
    weight: 25,
    effectKey: "season_cards_add_kkeut",
    amount: 12,
    params: { monthFrom: 7, monthTo: 9 },
    assetTag: "talisman:maple-leaf",
  },
  {
    id: "t_snow_rain",
    name: "눈비 부적",
    description: "득점하는 10~12월 카드마다 월 합 +12.",
    rarity: "common",
    price: 5,
    weight: 25,
    effectKey: "season_cards_add_kkeut",
    amount: 12,
    params: { monthFrom: 10, monthTo: 12 },
    assetTag: "talisman:snow-rain",
  },
  {
    id: "t_chaff_bind",
    name: "피붙이",
    description: "득점한 피값 1마다 월 합 +9.",
    rarity: "common",
    price: 5,
    weight: 25,
    effectKey: "chaff_value_add_kkeut",
    amount: 9,
    assetTag: "talisman:chaff-bind",
  },
  {
    id: "t_ribbon_maker",
    name: "띠장이",
    description: "득점하는 띠 카드마다 월 합 +15.",
    rarity: "common",
    price: 5,
    weight: 25,
    effectKey: "kind_cards_add_kkeut",
    amount: 15,
    params: { kind: "ribbon" },
    assetTag: "talisman:ribbon-maker",
  },
  {
    id: "t_animal_tracks",
    name: "산짐승 발자국",
    description: "득점하는 동물패마다 월 합 +18.",
    rarity: "common",
    price: 5,
    weight: 25,
    effectKey: "kind_cards_add_kkeut",
    amount: 18,
    params: { kind: "animal" },
    assetTag: "talisman:animal-tracks",
  },
  {
    id: "t_bright_polish",
    name: "광약",
    description: "득점하는 광 카드마다 월 합 +30.",
    rarity: "common",
    price: 6,
    weight: 20,
    effectKey: "kind_cards_add_kkeut",
    amount: 30,
    params: { kind: "bright" },
    assetTag: "talisman:bright-polish",
  },
  {
    id: "t_five_fingers",
    name: "다섯 손가락",
    description: "정확히 5장을 제출하면 월 합 +45와 배수 +1.",
    rarity: "common",
    price: 6,
    weight: 20,
    effectKey: "exact_submit_add",
    amount: 45,
    params: { cardCount: 5, addHeung: 1 },
    assetTag: "talisman:five-fingers",
  },
  {
    id: "t_lone_merchant",
    name: "독장수",
    description: "짓 없이 끗패만 낸 손이면 월 합 +55와 배수 +2.",
    rarity: "common",
    price: 6,
    weight: 20,
    effectKey: "jit_size_add",
    amount: 55,
    params: { maxJitCards: 0, addHeung: 2 },
    assetTag: "talisman:lone-merchant",
  },
  {
    id: "t_pair_knot",
    name: "짝패 매듭",
    description: "끗패가 땡 또는 장땡이면 배수 +2.",
    rarity: "common",
    price: 6,
    weight: 20,
    effectKey: "yaku_add_heung",
    amount: 2,
    params: { yakuIds: "ttaeng,jangttaeng" },
    assetTag: "talisman:pair-knot",
  },
  {
    id: "t_early_home",
    name: "조기 귀가",
    description: "판을 이길 때 남은 제출 1회마다 추가로 1냥을 얻음.",
    rarity: "common",
    price: 5,
    weight: 20,
    effectKey: "economy",
    amount: 1,
    params: { trigger: "round_win", perRemainingHand: true },
    assetTag: "talisman:early-home",
  },

  {
    id: "t_hong_thread",
    name: "홍실 매듭",
    description: "홍단을 새로 완성하면 배수 +4.",
    rarity: "uncommon",
    price: 7,
    weight: 14,
    effectKey: "collection_add_heung",
    amount: 4,
    params: { yakuId: "hongdan" },
    assetTag: "talisman:hong-thread",
  },
  {
    id: "t_cho_thread",
    name: "풀실 매듭",
    description: "초단을 새로 완성하면 배수 +4.",
    rarity: "uncommon",
    price: 7,
    weight: 14,
    effectKey: "collection_add_heung",
    amount: 4,
    params: { yakuId: "chodan" },
    assetTag: "talisman:cho-thread",
  },
  {
    id: "t_cheong_thread",
    name: "청실 매듭",
    description: "청단을 새로 완성하면 배수 +4.",
    rarity: "uncommon",
    price: 7,
    weight: 14,
    effectKey: "collection_add_heung",
    amount: 4,
    params: { yakuId: "cheongdan" },
    assetTag: "talisman:cheong-thread",
  },
  {
    id: "t_migratory_map",
    name: "철새 지도",
    description: "득점하는 새 그림패의 득점 효과를 1회 재발동.",
    rarity: "uncommon",
    price: 8,
    weight: 12,
    effectKey: "bird_retrigger",
    amount: 1,
    params: { tag: "bird" },
    assetTag: "talisman:migratory-map",
  },
  {
    id: "t_double_chaff_belt",
    name: "쌍피 전대",
    description: "득점한 피 카드마다 월 합 +1. 그중 쌍피는 추가로 월 합 +30.",
    rarity: "uncommon",
    price: 8,
    weight: 12,
    effectKey: "double_chaff_boost",
    amount: 30,
    params: { chaffValueBonus: 1 },
    assetTag: "talisman:double-chaff-belt",
  },
  {
    id: "t_leap_calendar",
    name: "반짓 셈판",
    description: "짓패의 월 합이 5의 배수여도 유효한 짓으로 인정됨.",
    rarity: "uncommon",
    price: 7,
    weight: 10,
    effectKey: "five_multiple_jit",
    params: { appliesTo: "jit" },
    assetTag: "talisman:leap-calendar",
  },
  {
    id: "t_empty_pouch",
    name: "빈 부적집",
    description: "비어 있는 부적 칸마다 배수 +1.",
    rarity: "uncommon",
    price: 7,
    weight: 12,
    effectKey: "empty_slots_add_heung",
    amount: 1,
    assetTag: "talisman:empty-pouch",
  },
  {
    id: "t_ring_ledger",
    name: "고리 장부",
    description: "보유 5냥마다 배수 +1, 최대 배수 +6.",
    rarity: "uncommon",
    price: 8,
    weight: 12,
    effectKey: "money_add_heung",
    amount: 1,
    params: { moneyStep: 5, maxHeung: 6 },
    assetTag: "talisman:ring-ledger",
  },
  {
    id: "t_jit_anvil",
    name: "짓모루",
    description: "짓에 들어간 카드 한 장마다 배수 +1. 길게 낼수록 커집니다.",
    rarity: "uncommon",
    price: 8,
    weight: 10,
    effectKey: "jit_add_heung",
    amount: 1,
    params: { perJitCard: true },
    assetTag: "talisman:jit-anvil",
  },
  {
    id: "t_sweep_broom",
    name: "싹쓸이 빗자루",
    description: "제출한 다섯 장이 모두 서로 다른 월이면 월 합 +60과 배수 +2.",
    rarity: "uncommon",
    price: 8,
    weight: 12,
    effectKey: "all_distinct_months_add",
    amount: 60,
    params: { minCards: 5, addHeung: 2 },
    assetTag: "talisman:sweep-broom",
  },
  {
    id: "t_mutual_aid",
    name: "품앗이",
    description: "첫 득점 카드에 손질이 있으면 그 카드의 득점 효과를 1회 재발동.",
    rarity: "uncommon",
    price: 8,
    weight: 10,
    effectKey: "first_card_retrigger",
    amount: 1,
    params: { requiresEnhancement: true },
    assetTag: "talisman:mutual-aid",
  },
  {
    id: "t_market_rumor",
    name: "장터 소문",
    description: "장터의 첫 물건 교체는 무료지만 이후 교체 비용이 1냥씩 더 빠르게 오름.",
    rarity: "uncommon",
    price: 7,
    weight: 10,
    effectKey: "economy",
    params: { firstRerollFree: true, extraRerollIncrement: 1 },
    assetTag: "talisman:market-rumor",
  },

  {
    id: "t_goblin_mirror",
    name: "도깨비 거울",
    description: "바로 왼쪽 부적의 점수 효과를 복사. 거울과 경제 효과는 복사하지 않음.",
    rarity: "rare",
    price: 11,
    weight: 6,
    effectKey: "copy_left_score",
    params: { excludesCopy: true, excludesEconomy: true },
    assetTag: "talisman:goblin-mirror",
  },
  {
    id: "t_chrysanthemum_cup",
    name: "국진 술잔",
    description: "9월 술잔이 동물패와 쌍피를 동시에 만족하고 득점 효과를 1회 재발동.",
    rarity: "rare",
    price: 11,
    weight: 6,
    effectKey: "cup_dual_role",
    amount: 1,
    params: { simultaneousRoles: true },
    assetTag: "talisman:chrysanthemum-cup",
  },
  {
    id: "t_full_moon_screen",
    name: "만월 병풍",
    description: "8월 카드는 족보 판정에서 광으로도 취급.",
    rarity: "rare",
    price: 10,
    weight: 6,
    effectKey: "month_counts_as_bright",
    params: { month: 8 },
    assetTag: "talisman:full-moon-screen",
  },
  {
    id: "t_cardsharp_touch",
    name: "타짜의 손끝",
    description: "각 손의 첫 득점 카드를 2회 추가 발동.",
    rarity: "rare",
    price: 12,
    weight: 5,
    effectKey: "first_card_retrigger",
    amount: 2,
    assetTag: "talisman:cardsharp-touch",
  },
  {
    id: "t_cremation_deed",
    name: "화형 문서",
    description: "손마다 첫 득점 피 1장을 끝난 뒤 소각하고, 판마다 한 번 배수가 영구적으로 +0.08 성장.",
    rarity: "rare",
    price: 11,
    weight: 5,
    effectKey: "burn_chaff_growth",
    factor: 1.08,
    params: { growthPerBurn: 0.08, maxGrowthsPerRound: 1 },
    assetTag: "talisman:cremation-deed",
  },
  {
    id: "t_twelve_panel_calendar",
    name: "열두 폭 달력",
    description: "이번 판에 처음 득점한 서로 다른 월마다 배수가 +0.15 성장하고 다음 판에 초기화.",
    rarity: "rare",
    price: 11,
    weight: 5,
    effectKey: "month_diversity_multiplier",
    factor: 0.15,
    params: { resetEachRound: true },
    assetTag: "talisman:twelve-panel-calendar",
  },
  {
    id: "t_go_bond_deed",
    name: "고박 문서",
    description: "고에 성공한 이번 승부의 배수를 ×1.5. 고 실패 시 2냥을 잃음.",
    rarity: "rare",
    price: 11,
    weight: 5,
    effectKey: "go_chain_multiplier",
    factor: 1.5,
    params: { failMoneyLoss: 2 },
    assetTag: "talisman:go-bond-deed",
  },
  {
    id: "t_over_shoulder_secret",
    name: "어깨너머 비법",
    description: "각 족보는 자기 레벨과 가장 높은 족보 레벨-2 중 큰 값을 사용.",
    rarity: "rare",
    price: 12,
    weight: 4,
    effectKey: "borrow_yaku_level",
    params: { highestLevelOffset: 2 },
    assetTag: "talisman:over-shoulder-secret",
  },

  {
    id: "t_phoenix_seal",
    name: "불사조의 인장",
    description: "판에서 처음 소각된 일반 패가 무작위 판본을 얻은 복사본 2장으로 돌아옴.",
    rarity: "legendary",
    price: 16,
    weight: 1,
    effectKey: "score_then_burn",
    params: { trigger: "first_burn_each_round", copies: 2, randomEdition: true },
    assetTag: "talisman:phoenix-seal",
  },
  {
    id: "t_table_reader",
    name: "판을 읽는 자",
    description: "가장 오른쪽의 복사 불가 부적 점수 효과를 1회 더 발동.",
    rarity: "legendary",
    price: 16,
    weight: 1,
    effectKey: "copy_neighbors",
    amount: 1,
    params: { target: "rightmost_noncopyable" },
    assetTag: "talisman:table-reader",
  },

  /* ------------------------------------------------------------------ *
   * 연계 조커.
   *
   * 하나만 놓고 보면 값이 잘 안 나오고, 옆에 놓인 다른 부적이나 손에 남긴
   * 카드가 있어야 의미가 생기는 종류다. 일부러 서로 반대로 당기는 짝을
   * 만들어 뒀다 — 미련↔다섯 손가락, 품삯 나눔↔빈 사당, 새것 애호↔비결서,
   * 무광 연습↔광약. 둘 다 사면 손해가 되게 두는 것이 요점이다.
   * ------------------------------------------------------------------ */
  {
    id: "t_lingering_hand",
    name: "미련",
    description: "제출하지 않고 손에 남긴 카드 한 장마다 배수 +0.5.",
    rarity: "common",
    price: 6,
    weight: 18,
    effectKey: "held_cards_add_heung",
    amount: 0.5,
    assetTag: "talisman:lingering-hand",
  },
  {
    id: "t_moonlit_keep",
    name: "달 지킴이",
    description: "손에 들고만 있는 광 한 장마다 배수 ×1.4.",
    rarity: "rare",
    price: 11,
    weight: 6,
    effectKey: "held_kind_multiply_heung",
    factor: 1.4,
    params: { kind: "bright" },
    assetTag: "talisman:moonlit-keep",
  },
  {
    id: "t_thrift_granary",
    name: "곳간 셈",
    description: "남은 버리기 1회마다 월 합 +40.",
    rarity: "common",
    price: 7,
    weight: 16,
    effectKey: "discards_left_add_kkeut",
    amount: 40,
    assetTag: "talisman:thrift-granary",
  },
  {
    id: "t_haggler_abacus",
    name: "삯꾼 주판",
    description: "가진 다른 부적들의 값 3냥마다 배수 +1.",
    rarity: "uncommon",
    price: 9,
    weight: 10,
    effectKey: "talisman_value_add_heung",
    amount: 1,
    params: { priceStep: 3 },
    assetTag: "talisman:haggler-abacus",
  },
  {
    id: "t_crowded_shrine",
    name: "빼곡한 사당",
    description: "부적 칸이 하나도 비어 있지 않으면 배수 ×1.8.",
    rarity: "uncommon",
    price: 9,
    weight: 11,
    effectKey: "full_slots_multiply_heung",
    factor: 1.8,
    assetTag: "talisman:crowded-shrine",
  },
  {
    id: "t_first_taste",
    name: "첫맛",
    description: "이번 여정에서 두 번 미만 낸 끗패로 득점하면 배수 ×1.9.",
    rarity: "rare",
    price: 10,
    weight: 7,
    effectKey: "fresh_yaku_multiply_heung",
    factor: 1.9,
    params: { maxTimesPlayed: 2 },
    assetTag: "talisman:first-taste",
  },
  {
    id: "t_mangtong_lover",
    name: "망통쟁이",
    description: "망통으로 득점하면 월 합이 3배가 됩니다.",
    rarity: "uncommon",
    price: 8,
    weight: 12,
    effectKey: "yaku_multiply_kkeut",
    factor: 3,
    params: { yakuIds: "mangtong" },
    assetTag: "talisman:mangtong-lover",
  },
  {
    id: "t_long_jit_thief",
    name: "긴 짓 도둑",
    description: "짓의 월 합이 30 이상이면 배수 ×2.2.",
    rarity: "rare",
    price: 12,
    weight: 6,
    effectKey: "jit_sum_multiply_heung",
    factor: 2.2,
    params: { minJitSum: 30 },
    assetTag: "talisman:long-jit-thief",
  },
  {
    id: "t_dark_practice",
    name: "무광 연습",
    description: "광 없이 득점한 손마다 배수가 영구적으로 +0.35 성장. 광이 득점하면 0으로 돌아갑니다.",
    rarity: "uncommon",
    price: 9,
    weight: 10,
    effectKey: "bright_drought_growth",
    amount: 0.35,
    assetTag: "talisman:dark-practice",
  },
  {
    id: "t_devouring_dagger",
    name: "제물 단도",
    description: "판이 시작될 때 바로 오른쪽 부적을 소각하고, 그 값 1냥마다 배수가 영구적으로 +0.25 성장.",
    rarity: "legendary",
    price: 14,
    weight: 3,
    effectKey: "devour_neighbor",
    amount: 0.25,
    assetTag: "talisman:devouring-dagger",
  },

  /* ------------------------------------------------------------------ *
   * 이름난 끗패를 노리는 조커.
   *
   * 특정 끗패 하나만 보고 사는 물건이라, 맞았을 때는 확실히 갚아야 한다.
   * 만들기 어려운 순서대로 배수가 커진다 — 알리(1·2월)는 흔하고, 38광땡은
   * 3월 광과 8월 광 두 장을 한 손에 쥐어야 한다.
   *
   * 같은 끗패의 비결서와 겹쳐 사면 기본 배수와 곱 배수가 같이 붙는다. 하나의
   * 끗패를 파는 빌드가 성립하라고 일부러 그렇게 뒀다.
   * ------------------------------------------------------------------ */
  {
    id: "t_ali_charm",
    name: "알리 부적",
    description: "끗패가 알리(1·2월)면 월 합 +40, 배수 ×1.8.",
    rarity: "common",
    price: 7,
    weight: 16,
    effectKey: "yaku_multiply_heung",
    amount: 40,
    factor: 1.8,
    params: { yakuIds: "ali" },
    assetTag: "talisman:ali-charm",
  },
  {
    id: "t_gabo_charm",
    name: "갑오 부적",
    description: "끗패가 갑오(끝자리 9)면 월 합 +45, 배수 ×1.7.",
    rarity: "common",
    price: 7,
    weight: 16,
    effectKey: "yaku_multiply_heung",
    amount: 45,
    factor: 1.7,
    params: { yakuIds: "gabo" },
    assetTag: "talisman:gabo-charm",
  },
  {
    id: "t_jangttaeng_charm",
    name: "장땡 부적",
    description: "끗패가 장땡(10월 두 장)이면 월 합 +70, 배수 ×2.4.",
    rarity: "rare",
    price: 11,
    weight: 7,
    effectKey: "yaku_multiply_heung",
    amount: 70,
    factor: 2.4,
    params: { yakuIds: "jangttaeng" },
    assetTag: "talisman:jangttaeng-charm",
  },
  {
    id: "t_gwangttaeng_charm",
    name: "광땡 부적",
    description: "끗패가 광땡이면 월 합 +90, 배수 ×3.",
    rarity: "rare",
    price: 13,
    weight: 5,
    effectKey: "yaku_multiply_heung",
    amount: 90,
    factor: 3,
    params: { yakuIds: "gwangttaeng_13,gwangttaeng_18,gwangttaeng_38" },
    assetTag: "talisman:gwangttaeng-charm",
  },
  {
    id: "t_sampal_seal",
    name: "삼팔 봉인",
    description: "끗패가 38광땡이면 월 합 +150, 배수 ×5. 이 게임에서 가장 좁고 가장 큰 한 방.",
    rarity: "legendary",
    price: 18,
    weight: 2,
    effectKey: "yaku_multiply_heung",
    amount: 150,
    factor: 5,
    params: { yakuIds: "gwangttaeng_38" },
    assetTag: "talisman:sampal-seal",
  },
] as const satisfies readonly TalismanDefinition[];

export const TALISMAN_BY_ID = Object.fromEntries(
  TALISMANS.map((definition) => [definition.id, definition]),
) as Record<string, (typeof TALISMANS)[number]>;

/** Tooltip/shop copy kept separate from the numeric description so every charm
 * states exactly when the rule is evaluated. */
export function getTalismanTimingText(definition: TalismanDefinition): string {
  switch (definition.effectKey) {
    case "devour_neighbor":
      return "발동 시점 · 다음 달 시작 시";
    case "threshold_relief":
      return "적용 시점 · 판 목표를 정할 때 상시";
    case "settlement_multiplier":
      return "발동 시점 · 판 승리 정산 시";
    case "fail_rescue":
      return "발동 시점 · 고 실패가 확정될 때";
    case "economy":
      return "적용 시점 · 장터 또는 판 정산 조건을 만족할 때";
    case "five_multiple_jit":
    case "cup_dual_role":
    case "month_counts_as_bright":
    case "all_kind_wild":
    case "borrow_yaku_level":
      return "적용 시점 · 보유 중 모든 제출 판정에 상시";
    case "unify_month_once":
      return "발동 시점 · 매 판 첫 제출 1회, 가장 유리한 월을 자동 선택";
    case "score_then_burn":
      return "발동 시점 · 제출 점수를 낸 직후 복사본을 소각";
    case "bright_drought_growth":
    case "burn_chaff_growth":
      return "발동 시점 · 제출 조건을 만족하면 점수 적용 후 영구 성장";
    default:
      return "발동 시점 · 핸드 제출 점수 계산 중";
  }
}
