import type {
  BookDefinition,
  CardModifierDefinition,
  EditionId,
  EnhancementId,
  ForbiddenDefinition,
  PainterDefinition,
  SealId,
} from "../types";

export type CatalogBookDefinition = BookDefinition & { description: string };
export type CatalogForbiddenDefinition = ForbiddenDefinition;

export const PAINTER_CARDS = [
  {
    id: "p_month_plus",
    name: "이월",
    description: "선택 카드 최대 2장의 월을 +1. 12월 다음은 1월.",
    rarity: "common",
    price: 4,
    weight: 20,
    effectKey: "month_plus",
    minTargets: 1,
    maxTargets: 2,
    assetTag: "painter:month-plus",
  },
  {
    id: "p_month_minus",
    name: "역월",
    description: "선택 카드 최대 2장의 월을 -1. 1월 전은 12월.",
    rarity: "common",
    price: 4,
    weight: 20,
    effectKey: "month_minus",
    minTargets: 1,
    maxTargets: 2,
    assetTag: "painter:month-minus",
  },
  {
    id: "p_overpaint",
    name: "덧칠",
    description: "첫 번째 카드가 두 번째 카드의 월을 복사.",
    rarity: "common",
    price: 4,
    weight: 25,
    effectKey: "copy_month",
    minTargets: 2,
    maxTargets: 2,
    assetTag: "painter:overpaint",
  },
  {
    id: "p_join_months",
    name: "이어붙이기",
    description: "선택한 두 카드의 월을 둘 중 하나로 통일.",
    rarity: "uncommon",
    price: 5,
    weight: 14,
    effectKey: "unify_two_months",
    minTargets: 2,
    maxTargets: 2,
    assetTag: "painter:join-months",
  },
  {
    id: "p_rubbing",
    name: "탁본",
    description: "선택 카드 1장의 정확한 복사본을 덱에 추가.",
    rarity: "uncommon",
    price: 6,
    weight: 10,
    effectKey: "duplicate",
    minTargets: 1,
    maxTargets: 1,
    assetTag: "painter:rubbing",
  },
  {
    id: "p_burn",
    name: "소각",
    description: "선택 카드 최대 2장을 덱에서 영구 제거.",
    rarity: "common",
    price: 5,
    weight: 16,
    effectKey: "burn",
    minTargets: 1,
    maxTargets: 2,
    assetTag: "painter:burn",
  },
  {
    id: "p_promote",
    name: "승격",
    description: "선택 카드 1장을 피→띠→동물패 중 한 단계 승격. 띠가 되면 그룹을 선택.",
    rarity: "common",
    price: 5,
    weight: 18,
    effectKey: "promote_kind",
    minTargets: 1,
    maxTargets: 1,
    assetTag: "painter:promote",
  },
  {
    id: "p_double_chaff",
    name: "쌍피",
    description: "일반 피 카드 1장을 쌍피로 변경.",
    rarity: "common",
    price: 4,
    weight: 25,
    effectKey: "double_chaff",
    minTargets: 1,
    maxTargets: 1,
    assetTag: "painter:double-chaff",
  },
  {
    id: "p_ribbon_dye",
    name: "색동띠",
    description: "피 또는 띠 1장을 띠로 만들고 홍·초·청 그룹을 선택.",
    rarity: "common",
    price: 4,
    weight: 25,
    effectKey: "ribbon_dye",
    minTargets: 1,
    maxTargets: 1,
    assetTag: "painter:ribbon-dye",
  },
  {
    id: "p_bird_mark",
    name: "새김",
    description: "피 1장을 새 동물패로 만들고 월을 2·4·8월 중 하나로 선택.",
    rarity: "uncommon",
    price: 5,
    weight: 15,
    effectKey: "bird_mark",
    minTargets: 1,
    maxTargets: 1,
    assetTag: "painter:bird-mark",
  },
  {
    id: "p_rain_mark",
    name: "빗금",
    description: "선택 카드 1장에 비 태그를 추가.",
    rarity: "uncommon",
    price: 5,
    weight: 12,
    effectKey: "rain_mark",
    minTargets: 1,
    maxTargets: 1,
    assetTag: "painter:rain-mark",
  },
  {
    id: "p_lacquer",
    name: "옻칠",
    description: "선택 카드 최대 2장에 무작위 손질을 부여.",
    rarity: "uncommon",
    price: 6,
    weight: 10,
    effectKey: "apply_enhancement",
    minTargets: 1,
    maxTargets: 2,
    assetTag: "painter:lacquer",
  },
  {
    id: "p_woodblock",
    name: "판각",
    description: "선택 카드 1장에 무작위 판본을 부여.",
    rarity: "rare",
    price: 7,
    weight: 6,
    effectKey: "apply_edition",
    minTargets: 1,
    maxTargets: 1,
    assetTag: "painter:woodblock",
  },
  {
    id: "p_stamp",
    name: "낙관",
    description: "선택 카드 1장에 선택한 기본 낙관을 부여.",
    rarity: "uncommon",
    price: 6,
    weight: 9,
    effectKey: "apply_seal",
    minTargets: 1,
    maxTargets: 1,
    assetTag: "painter:stamp",
  },
  {
    id: "p_reprise",
    name: "되새김",
    description: "이번 판에서 마지막으로 사용한 화공패 또는 비결서를 복사.",
    rarity: "rare",
    price: 8,
    weight: 5,
    effectKey: "repeat_last_consumable",
    minTargets: 0,
    maxTargets: 0,
    assetTag: "painter:reprise",
  },
] as const satisfies readonly PainterDefinition[];

export const FORBIDDEN_CARDS = [
  {
    id: "f_first_full_moon",
    name: "정월대보름",
    description: "고른 패를 정월로 물들이고, 마지막으로 고른 한 장을 제물로 태우는 금단패.",
    benefit: "선택 카드 2~5장을 1월로 변경.",
    cost: "마지막으로 선택한 카드 1장을 영구 소각.",
    price: 10,
    targetKind: "card",
    minTargets: 2,
    maxTargets: 5,
    targetPrompt: "1월로 바꿀 패를 2~5장 고르세요. 마지막 선택은 제물이 됩니다.",
    effectKey: "all_to_january",
    assetTag: "forbidden:first-full-moon",
  },
  {
    id: "f_clone_ritual",
    name: "복제굿",
    description: "완벽한 복사본 둘을 얻는 대신 이번 판의 손패를 줄이는 의식.",
    benefit: "선택 카드의 정확한 복사본 2장을 덱에 추가.",
    cost: "이번 판의 손패 크기 -1.",
    price: 11,
    targetKind: "card",
    minTargets: 1,
    maxTargets: 1,
    targetPrompt: "복제할 패 1장을 고르세요.",
    effectKey: "double_duplicate_hand_penalty",
    assetTag: "forbidden:clone-ritual",
  },
  {
    id: "f_bright_descent",
    name: "광내림",
    description: "값비싼 대가를 치르고 일반 패 한 장에 광의 격을 내림.",
    benefit: "선택 카드 1장을 광으로 승격.",
    cost: "사용 시 6냥 추가 지불. 부족하면 사용 불가.",
    price: 12,
    targetKind: "card",
    minTargets: 1,
    maxTargets: 1,
    targetPrompt: "광이 아닌 패 1장을 고르세요.",
    additionalCost: 6,
    effectKey: "make_bright_pay",
    assetTag: "forbidden:bright-descent",
  },
  {
    id: "f_white_chaff",
    name: "백피",
    description: "고른 패를 강한 피로 바꾸어 한 종류에 모든 가능성을 거는 금단패.",
    benefit: "선택 카드 최대 5장을 피로 바꾸고 각 카드에 영구 월 합 +4.",
    cost: "바뀐 카드가 제공하던 다른 종류 족보 가능성을 잃음.",
    price: 10,
    targetKind: "card",
    minTargets: 1,
    maxTargets: 5,
    targetPrompt: "피로 바꿀 패를 1~5장 고르세요.",
    effectKey: "all_hand_chaff_bonus",
    assetTag: "forbidden:white-chaff",
  },
  {
    id: "f_monthless",
    name: "팔방패",
    description: "광·동물·띠·피 어느 수집줄에도 들어가지만 짓의 월 합에는 보탬이 되지 않는 패.",
    benefit: "선택 카드 1장을 모든 종류로 취급.",
    cost: "그 카드의 월값을 0으로 설정.",
    price: 12,
    targetKind: "card",
    minTargets: 1,
    maxTargets: 1,
    targetPrompt: "모든 월을 잇게 할 패 1장을 고르세요.",
    effectKey: "wild_month_zero_base",
    assetTag: "forbidden:eight-directions",
  },
  {
    id: "f_great_burn",
    name: "큰 소각",
    description: "덱을 빠르게 줄이고 돈을 받지만 제물은 고를 수 없는 거래.",
    benefit: "강화가 없는 일반 카드 최대 5장을 무작위 소각하고 18냥 획득.",
    cost: "소각 대상을 선택할 수 없음.",
    price: 8,
    targetKind: "none",
    minTargets: 0,
    maxTargets: 0,
    targetPrompt: "소각 대상은 자동으로 정해집니다.",
    effectKey: "random_burn_for_money",
    assetTag: "forbidden:great-burn",
  },
  {
    id: "f_talisman_possession",
    name: "부적 빙의",
    description: "고른 부적에 음각의 힘을 들이는 대신 손패 한 칸을 내주는 의식.",
    benefit: "선택 부적 1개에 음각 판본 부여.",
    cost: "이번 판의 손패 크기 -1.",
    price: 13,
    targetKind: "talisman",
    minTargets: 1,
    maxTargets: 1,
    targetPrompt: "음각을 새길 부적 1개를 고르세요.",
    effectKey: "engrave_talisman_hand_penalty",
    assetTag: "forbidden:talisman-possession",
  },
  {
    id: "f_twelve_ritual",
    name: "열두 굿",
    description: "모든 족보를 깨우는 대신 가진 돈을 모두 굿판에 바침.",
    benefit: "발견한 모든 족보 레벨 +1.",
    cost: "보유한 냥이 0이 됨.",
    price: 14,
    targetKind: "none",
    minTargets: 0,
    maxTargets: 0,
    targetPrompt: "대상 선택 없이 모든 족보에 적용됩니다.",
    effectKey: "level_all_money_zero",
    assetTag: "forbidden:twelve-ritual",
  },
  {
    id: "f_inheritance",
    name: "전승",
    description: "중첩 가능한 부적의 왼쪽 부적을 없애고, 고른 부적을 하나 더 만드는 되돌릴 수 없는 선택.",
    benefit: "중첩 가능한 선택 부적을 복제해 발동 효과를 2회로 만듦.",
    cost: "선택 부적 바로 왼쪽의 부적을 영구 파괴.",
    price: 14,
    targetKind: "talisman",
    minTargets: 1,
    maxTargets: 1,
    targetPrompt: "중첩 가능한 부적 1개를 고르세요. 바로 왼쪽 부적이 제물이 됩니다.",
    effectKey: "sacrifice_copy",
    assetTag: "forbidden:inheritance",
  },
  {
    id: "f_spirit",
    name: "혼백",
    description: "모든 부적을 제물로 삼아 전설 부적 하나를 불러냄.",
    benefit: "무작위 전설 부적 1개 생성.",
    cost: "보유한 다른 부적 전부 파괴.",
    price: 15,
    targetKind: "none",
    minTargets: 0,
    maxTargets: 0,
    targetPrompt: "대상 선택 없이 보유 부적 전부를 제물로 바칩니다.",
    effectKey: "legendary_destroy_others",
    assetTag: "forbidden:spirit",
  },
] as const satisfies readonly CatalogForbiddenDefinition[];

/** 끗패 족보 14종의 비결서. 한 장에 해당 족보 레벨 +1. */
export const BOOKS = [
  {
    id: "b_mangtong",
    name: "망통 비결",
    description: "이번 판 동안 망통 레벨 +1.",
    yakuId: "mangtong",
    price: 3,
    rarity: "common",
    weight: 24,
    assetTag: "book:mangtong",
  },
  {
    id: "b_kkeut",
    name: "끗 비결",
    description: "이번 판 동안 끗 레벨 +1.",
    yakuId: "kkeut",
    price: 3,
    rarity: "common",
    weight: 26,
    assetTag: "book:kkeut",
  },
  {
    id: "b_gabo",
    name: "갑오 비결",
    description: "이번 판 동안 갑오 레벨 +1.",
    yakuId: "gabo",
    price: 4,
    rarity: "common",
    weight: 22,
    assetTag: "book:gabo",
  },
  {
    id: "b_seryuk",
    name: "세륙 비결",
    description: "이번 판 동안 세륙 레벨 +1.",
    yakuId: "seryuk",
    price: 4,
    rarity: "common",
    weight: 18,
    assetTag: "book:seryuk",
  },
  {
    id: "b_jangsa",
    name: "장사 비결",
    description: "이번 판 동안 장사 레벨 +1.",
    yakuId: "jangsa",
    price: 5,
    rarity: "common",
    weight: 18,
    assetTag: "book:jangsa",
  },
  {
    id: "b_jangpping",
    name: "장삥 비결",
    description: "이번 판 동안 장삥 레벨 +1.",
    yakuId: "jangpping",
    price: 5,
    rarity: "common",
    weight: 16,
    assetTag: "book:jangpping",
  },
  {
    id: "b_gupping",
    name: "구삥 비결",
    description: "이번 판 동안 구삥 레벨 +1.",
    yakuId: "gupping",
    price: 5,
    rarity: "uncommon",
    weight: 15,
    assetTag: "book:gupping",
  },
  {
    id: "b_doksa",
    name: "독사 비결",
    description: "이번 판 동안 독사 레벨 +1.",
    yakuId: "doksa",
    price: 6,
    rarity: "uncommon",
    weight: 14,
    assetTag: "book:doksa",
  },
  {
    id: "b_ali",
    name: "알리 비결",
    description: "이번 판 동안 알리 레벨 +1.",
    yakuId: "ali",
    price: 6,
    rarity: "uncommon",
    weight: 13,
    assetTag: "book:ali",
  },
  {
    id: "b_ttaeng",
    name: "땡 비결",
    description: "이번 판 동안 땡 레벨 +1.",
    yakuId: "ttaeng",
    price: 7,
    rarity: "uncommon",
    weight: 12,
    assetTag: "book:ttaeng",
  },
  {
    id: "b_jangttaeng",
    name: "장땡 비결",
    description: "이번 판 동안 장땡 레벨 +1.",
    yakuId: "jangttaeng",
    price: 8,
    rarity: "rare",
    weight: 8,
    assetTag: "book:jangttaeng",
  },
  {
    id: "b_gwangttaeng_13",
    name: "13광땡 비결",
    description: "이번 판 동안 13광땡 레벨 +1.",
    yakuId: "gwangttaeng_13",
    price: 9,
    rarity: "rare",
    weight: 5,
    assetTag: "book:gwangttaeng-13",
  },
  {
    id: "b_gwangttaeng_18",
    name: "18광땡 비결",
    description: "이번 판 동안 18광땡 레벨 +1.",
    yakuId: "gwangttaeng_18",
    price: 9,
    rarity: "rare",
    weight: 4,
    assetTag: "book:gwangttaeng-18",
  },
  {
    id: "b_gwangttaeng_38",
    name: "38광땡 비결",
    description: "이번 판 동안 38광땡 레벨 +1.",
    yakuId: "gwangttaeng_38",
    price: 10,
    rarity: "legendary",
    weight: 3,
    assetTag: "book:gwangttaeng-38",
  },
  { id: "b_hongdan", name: "홍단 수집 비결", description: "홍단 점수 +1. 완성 시 버리기 +1을 해금.", yakuId: "hongdan", price: 6, rarity: "uncommon", weight: 12, assetTag: "book:hongdan" },
  { id: "b_chodan", name: "초단 수집 비결", description: "초단 점수 +1. 완성 시 버리기 +1을 해금.", yakuId: "chodan", price: 6, rarity: "uncommon", weight: 12, assetTag: "book:chodan" },
  { id: "b_cheongdan", name: "청단 수집 비결", description: "청단 점수 +1. 완성 시 버리기 +1을 해금.", yakuId: "cheongdan", price: 6, rarity: "uncommon", weight: 12, assetTag: "book:cheongdan" },
  { id: "b_godori", name: "고도리 수집 비결", description: "고도리 점수 +1. 완성 시 짓 5배수 규칙을 해금.", yakuId: "godori", price: 7, rarity: "rare", weight: 9, assetTag: "book:godori" },
  { id: "b_rain_three_brights", name: "비삼광 수집 비결", description: "비삼광 점수 +1. 광 비결은 고 문턱을 5% 낮춤.", yakuId: "rain_three_brights", price: 7, rarity: "rare", weight: 8, assetTag: "book:rain-three-brights" },
  { id: "b_three_brights", name: "삼광 수집 비결", description: "삼광 점수 +1. 광 비결은 고 문턱을 5% 낮춤.", yakuId: "three_brights", price: 7, rarity: "rare", weight: 8, assetTag: "book:three-brights" },
  { id: "b_four_brights", name: "사광 수집 비결", description: "사광 점수 +1. 광 비결은 고 문턱을 5% 낮춤.", yakuId: "four_brights", price: 8, rarity: "rare", weight: 6, assetTag: "book:four-brights" },
  { id: "b_five_brights", name: "오광 수집 비결", description: "오광 점수 +1. 광 비결은 고 문턱을 5% 낮춤.", yakuId: "five_brights", price: 10, rarity: "legendary", weight: 3, assetTag: "book:five-brights" },
] as const satisfies readonly CatalogBookDefinition[];

export const ENHANCEMENTS = [
  {
    id: "inked",
    name: "먹칠",
    description: "득점할 때 월 합 +3.",
    assetTag: "enhancement:inked",
  },
  {
    id: "scarlet",
    name: "홍칠",
    description: "득점할 때 배수 +3.",
    assetTag: "enhancement:scarlet",
  },
  {
    id: "wild",
    name: "만능화",
    description: "족보 판정에서 모든 종류로 취급하지만 점수는 카드의 원래 월값으로 계산.",
    assetTag: "enhancement:wild",
  },
  {
    id: "glass",
    name: "유리패",
    description: "득점 시 배수 ×1.75, 이후 25% 확률로 영구 소각.",
    assetTag: "enhancement:glass",
  },
  {
    id: "steel",
    name: "강철패",
    description: "손에 남아 있으면 배수 ×1.25.",
    assetTag: "enhancement:steel",
  },
  {
    id: "stone",
    name: "돌패",
    description: "월과 종류를 잃고 모든 손에서 득점하며 월값 12로 계산.",
    assetTag: "enhancement:stone",
  },
  {
    id: "coin",
    name: "금전패",
    description: "판 종료 때 손에 남아 있으면 +2냥.",
    assetTag: "enhancement:coin",
  },
  {
    id: "fortune",
    name: "복패",
    description: "득점 시 20% 확률로 배수 +12, 별도로 8% 확률로 +12냥.",
    assetTag: "enhancement:fortune",
  },
] as const satisfies readonly CardModifierDefinition<EnhancementId>[];

export const EDITIONS = [
  {
    id: "gold_leaf",
    name: "금박",
    description: "카드 또는 부적의 점수 효과에 월 합 +5.",
    assetTag: "edition:gold-leaf",
  },
  {
    id: "mother_of_pearl",
    name: "자개",
    description: "카드 또는 부적의 점수 효과에 배수 +6.",
    assetTag: "edition:mother-of-pearl",
  },
  {
    id: "five_color",
    name: "오색",
    description: "카드 또는 부적의 점수 효과에서 배수 ×1.35.",
    assetTag: "edition:five-color",
  },
  {
    id: "engraved",
    name: "음각",
    description: "부적에만 적용되며 부적 슬롯 +1.",
    assetTag: "edition:engraved",
  },
] as const satisfies readonly CardModifierDefinition<EditionId>[];

export const SEALS = [
  {
    id: "yellow",
    name: "황인",
    description: "카드가 득점하면 +2냥.",
    assetTag: "seal:yellow",
  },
  {
    id: "red",
    name: "홍인",
    description: "카드의 득점 효과를 1회 재발동.",
    assetTag: "seal:red",
  },
  {
    id: "blue",
    name: "청인",
    description: "판 종료 때 손에 남아 있으면 마지막 족보의 비결서를 생성.",
    assetTag: "seal:blue",
  },
  {
    id: "purple",
    name: "자인",
    description: "이 카드를 버리면 무작위 화공패를 생성.",
    assetTag: "seal:purple",
  },
] as const satisfies readonly CardModifierDefinition<SealId>[];

export const PAINTER_BY_ID = Object.fromEntries(
  PAINTER_CARDS.map((definition) => [definition.id, definition]),
) as Record<string, (typeof PAINTER_CARDS)[number]>;

export const FORBIDDEN_BY_ID = Object.fromEntries(
  FORBIDDEN_CARDS.map((definition) => [definition.id, definition]),
) as Record<string, (typeof FORBIDDEN_CARDS)[number]>;

export const BOOK_BY_ID = Object.fromEntries(
  BOOKS.map((definition) => [definition.id, definition]),
) as Record<string, (typeof BOOKS)[number]>;
